Add retry logic to wait until page was build

diff --git a/.github/workflows/library-release.yml b/.github/workflows/library-release.yml
--- a/.github/workflows/library-release.yml
+++ b/.github/workflows/library-release.yml
@@ -44,6 +44,26 @@ jobs:
         run: |
           ghga_common=$(curl -s "https://api.github.com/repos/ghga-de/charts/releases?per_page=300" | jq -r 'map(select(.tag_name | startswith("ghga-common"))) | sort_by(.published_at) | reverse | .[0] | .tag_name')
           ghga_common_version=${ghga_common#ghga-common-}
+
+          chart_pulled=0
+          # Wait until the Helm repository is updated with the new ghga-common version
+          for i in $(seq 1 10); do
+              helm repo update
+              echo "Attempt $i: pulling ghga/ghga-common version $CHART_VERSION..."
+              if helm pull ghga/ghga-common --version "$ghga_common_version"; then
+                  echo "Chart pulled successfully."
+                  chart_pulled=1
+                  break
+              fi
+              echo "Failed attempt $i. Retrying in $SLEEP_SECONDS seconds..."
+              sleep 5
+          done
+
+          if [ "$chart_pulled" -eq 0 ]; then
+            echo "Could not pull ghga/ghga-common version $ghga_common_version after 10 attempts."
+            exit 1
+          fi
+
           echo "Processing charts in directories: archive/ with library version $ghga_common_version"
           echo "GHGA_COMMON_VERSION=$ghga_common_version" >> $GITHUB_ENV
 
